[package]
name = "lscy_compactor"
version = "0.1.0"
authors = ["Scott Lott <me@scottlott.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bloom = "0.3.2"
scylla = "0.2.1"
tokio = "1.10.1"
